
# Helper function to get a target property
# This method checks if the target is an interface library, in which case it's a no-op
macro(get_target_property_safe _var _tgt _prop)
    set(${_var})
    if(TARGET ${_tgt})
        get_target_property(_type ${_tgt} TYPE)
        if(NOT _type STREQUAL "INTERFACE_LIBRARY")
            get_target_property(${_var} ${_tgt} ${_prop})
        endif()
    endif()
endmacro()

# Helper function to recursively find all dependenencies for a target
function(collect_all_dependencies var tgt)
    set(_seen)
    set(_todo ${tgt})
    while(_todo)
        list(GET _todo 0 _cur)
        list(REMOVE_AT _todo 0)
        if(NOT ${_cur} IN_LIST _seen)
            if(TARGET ${_cur})
                list(APPEND _seen ${_cur})
                get_target_property_safe(_ilibs ${_cur} LINK_LIBRARIES)
                if(_ilibs)
                    list(APPEND _todo ${_ilibs})
                endif()
            endif()
        endif()
    endwhile()
    set(${var} ${_seen} PARENT_SCOPE)
endfunction()

macro(set_license_info target lic_name lic_file)
    string(MAKE_C_IDENTIFIER ${target} _target_id)
    set( ${_target_id}_LICENSE_NAMES ${${_target_id}_LICENSE_NAMES} ${lic_name})
    set(${_target_id}_LICENSE_FILES ${${_target_id}_LICENSE_FILES} ${lic_file})
endmacro()

function(move_if_different temp_file file)
    if(EXISTS ${file})
       file(SHA1 ${temp_file} sha1_file_tmp)
       file(SHA1 ${file} sha1_file)
       if(${sha1_file_tmp} STREQUAL ${sha1_file})
          file(REMOVE ${temp_file})
       else()
          file(RENAME ${temp_file} ${file})
       endif()
    else()
        file(RENAME ${temp_file} ${file})
    endif()
endfunction()


# This function collects the license files for a given module
# !!! NOTE: MUST BE CALLED AFTER THE MODULE IS FULLY SET UP !!!
function(make_licenses target)
    set(license_output_dir ${CMAKE_CURRENT_BINARY_DIR}/generated/${target})
    set(lic_h ${license_output_dir}/licenses.h)
    set(lic_cpp ${license_output_dir}/licenses.cpp)
    set(lic_h_tmp ${lic_h}.tmp)
    set(lic_cpp_tmp ${lic_cpp}.tmp)
    message("Generating ${lic_h_tmp}...")
    message("Generating ${lic_cpp_tmp}...")
    collect_all_dependencies(_all_deps ${target})
    file(MAKE_DIRECTORY ${license_output_dir})
    file(REMOVE ${lic_h_tmp})
    file(REMOVE ${lic_cpp_tmp})
    file(APPEND ${lic_h_tmp} "// !!! GENERATED FILE !!! DO NOT EDIT !!!\n#pragma once\n\n")
    file(APPEND ${lic_h_tmp} "extern const char* licenses[][2]; // Name, Content\n")
    file(APPEND ${lic_cpp_tmp} "// !!! GENERATED FILE !!! DO NOT EDIT !!!\n#include \"licenses.h\"\n\n")
    file(APPEND ${lic_cpp_tmp} "const char* licenses[][2] = {\n")
    foreach(mod IN ITEMS ${_all_deps})
        string(MAKE_C_IDENTIFIER ${mod} _target_id)
        set(lic_names ${${_target_id}_LICENSE_NAMES})
        set(lic_files ${${_target_id}_LICENSE_FILES})
        if(lic_names AND lic_files)
            list(LENGTH lic_files list_len)
            math(EXPR last_index "${list_len} - 1")
            foreach(i RANGE 0 ${last_index})
                list(GET lic_names ${i} lic_name)
                list(GET lic_files ${i} lic)
                file(READ "${lic}" text)
                set(content "   { \"${lic_name}\", R\"(\n${text})\"},\n\n")
                file(APPEND "${lic_cpp_tmp}" "${content}")
            endforeach()
        endif()
    endforeach()
    file(APPEND ${lic_cpp_tmp} "    { nullptr, nullptr },\n")
    file(APPEND ${lic_cpp_tmp} "};\n")
    target_include_directories(${target} PRIVATE ${license_output_dir})
    move_if_different(${lic_h_tmp} ${lic_h})
    move_if_different(${lic_cpp_tmp} ${lic_cpp})
    target_sources(${target} PRIVATE ${lic_h} ${lic_cpp})
endfunction()
